"""Initial migration

Revision ID: faa58e9b86df
Revises: 1b93f0969307
Create Date: 2025-05-25 16:36:21.834399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa58e9b86df'
down_revision = '1b93f0969307'
branch_labels = None
depends_on = None


def upgrade():
    # Use raw SQL to recreate the table or skip the NOT NULL constraint for SQLite
    conn = op.get_bind()
    if conn.dialect.name == 'sqlite':
        # SQLite workaround: manually alter table or skip
        pass
    else:
        op.alter_column('evaluaciones', 'fecha', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluaciones', sa.Column('ip_hash', sa.VARCHAR(length=64), nullable=True))
    op.add_column('evaluaciones', sa.Column('user_agent_hash', sa.VARCHAR(length=64), nullable=True))
    op.alter_column('evaluaciones', 'fecha',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###